# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57c7ee2d0967c6830a5c1a4509c29b18e05ab2e28834e42db029011241cbc01869abcc990c7667c9b99e484929dc360ccb6bb28a596528441c0c704b96f81b4f

test:
  secret_key_base: 654451b9756d2d5e971692c6377c1042724e4914b59af460ae1ffdaec1ab3e020a36e5c2ce8636f1d6d10a1bc6c2417bfe6fd109eb1a6518e7d2d3832db57f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
